// <auto-generated />
using System;
using DawnxDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DawnxDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191015030042_201910151058")]
    partial class _201910151058
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DawnxDemo.Data.OneClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NormalA1");

                    b.Property<string>("NormalA2");

                    b.Property<int?>("Password");

                    b.Property<string>("UniqueA1");

                    b.Property<string>("UniqueA2");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.HasIndex("NormalA1", "NormalA2");

                    b.HasIndex("UniqueA1", "UniqueA2")
                        .IsUnique();

                    b.ToTable("OneClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
