// <auto-generated />
using System;
using DawnxDemo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DawnxDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191015031120_201910151110")]
    partial class _201910151110
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DawnxDemo.Data.OneClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Password");

                    b.Property<string>("UniqueA1")
                        .IsRequired();

                    b.Property<string>("UniqueA2")
                        .IsRequired();

                    b.Property<DateTime>("UniqueB1");

                    b.Property<DateTime>("UniqueB2");

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.HasIndex("UniqueA1", "UniqueA2")
                        .IsUnique();

                    b.HasIndex("UniqueB1", "UniqueB2")
                        .IsUnique();

                    b.ToTable("OneClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
